### ISSUE TITLE
Coroutine/trampoline effect

### ISSUE THREAD

**Issue by Caagr98** [polysemy-research/polysemy-zoo#64]
I noticed that `pogoStick` from [monad-coroutine](https://hackage.haskell.org/package/monad-coroutine) is very similar (type-wise) to `interpret`, which got me thinking: Would it be possible to implement an effect behaving similarly to that Coroutine transformer? As an example, I think this could probably be used for connecting an `Output` into an `Input`, without having to manually write either as a state machine, as is necessary if doing the same with `interpret`. (I'm not sure what would happen if either ends before the other though.)

**Comment by KingoftheHomeless** [comment]
Nope.

Due to fundamental issues with the `weave` abstraction, a well-behaved `Coroutine` effect is impossible to make in `Polysemy`.

To be technical, `CoroutineT` doesn't have a well-defined functorial state; i.e. it's not a `MonadTransControl`, and `weave` requires every carrier to be `MonadTransControl`.

The solution would be to ditch `weave`, but that's easier said than done; although I am working on it. The result would probably be too different to fall under the polysemy name, though.

**Comment by KingoftheHomeless** [comment]
See [Polysemy issue #264](https://github.com/polysemy-research/polysemy/issues/264) for a failed attempt at this.
